# Generated by Django 6.0.1 on 2026-01-31 10:57

import apps.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.models.managers.CustomUserManager()),
            ],
        ),
    ]
